name: Deploy Production

on:
  release:
    types: [published]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: zgamelogic/github-actions/.github/workflows/kubernetes-deploy.yaml@0.0.1
    with:
      applicationId: 4
      monitorIds: '4'
      environment: production
      deploymentName: cobble-bot
      imageName: cobble